# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  name:
    description: 'Friendly unique name'
    required: true
  host:
    description: 'Host'
    required: true
  user:
    description: 'User'
    required: true
  key:
    description: 'Key'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh ${{ inputs.name }} ${{ inputs.host }} ${{ inputs.user }} ${{ inputs.key }}
      shell: bash