# action.yml
name: 'Setup ssh'
description: 'setup ssh'
inputs:
  name:
    description: 'Friendly unique name'
    required: true
  host:
    description: 'Host'
    required: true
  user:
    description: 'User'
    required: true
  key:
    description: 'Key'
    required: true
runs:
  using: "composite"
  steps:
    - run: mkdir -p ~/.ssh/
      shell: bash
    - run: echo "${{ inputs.key }}" > ~/.ssh/${{ inputs.name }}
      shell: bash
    - run: chmod 600 ~/.ssh/${{ inputs.name }}
      shell: bash
    - run: |
        cat >>~/.ssh/config <<END
        Host ${{ inputs.name }}
          HostName ${{ inputs.host }}
          User ${{ inputs.user }}
          IdentityFile ~/.ssh/$1
          StrictHostKeyChecking no
        END